### ISSUE TITLE
Please use more meaningful messages in commits

### ISSUE THREAD

**Issue by JINKEHE** [Jeffershaw/UCL_DSML_note#2]
commits like "terrible thing" and "little change" are confusing to people who read your notes everyday

**Comment by Jeffershaw** [comment]
Really? Are you coming to study my committing message?

**Comment by Jeffershaw** [comment]
If so, I will show you what is saohua

**Comment by JINKEHE** [comment]
Really missed the time we wrote saohua in commits back in liverpool and solved the problem before everyone had.

**Comment by Jeffershaw** [comment]
And watched the previous group boom. BTW, did your tutor find your Megatron repository?

**Comment by JINKEHE** [comment]
wo jue de ta fa xian le
